POST http://localhost:3000/courses
Content-Type: application/json

{
  "title": "Course of Ruby!",
  "description": "This is a course of Ruby!"
}

###
GET http://localhost:3000/courses
###
GET http://localhost:3000/courses/1
###
DELETE http://localhost:3000/courses/1
###
PATCH  http://localhost:3000/courses/1
Content-Type: application/json

{
  "title": "Course of sofware engeniering",
  "description": "this is a course of sofware engeniering"
}