POST http://localhost:3000/courses
Content-Type: application/json

{
  "title": "",
  "description": ""
}

###
GET http://localhost:3000/courses
###
GET http://localhost:3000/courses/56251c33-2188-400a-a27d-1832251ed40c
###
DELETE http://localhost:3000/courses/66834c18-9544-4857-96bd-0ba9c29409e5
###
PATCH  http://localhost:3000/courses/56251c33-2188-400a-a27d-1832251ed40c
Content-Type: application/json

{
  "title": "Course of sofware engeniering",
  "description": "this is a course of sofware engeniering"
}