POST http://localhost:3000/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZjEyMDEwMy1mMzIzLTRjZTAtYjFlNC04ZjYwMmNiNDIyNjYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTU0MDM5MX0.LqHJNOAFs909VfMwJbJ6ZYXYj-mjJPvhUEDa5mvrUsM

{
  "title": "course of nextJs"  
}

###
GET http://localhost:3000/courses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZjEyMDEwMy1mMzIzLTRjZTAtYjFlNC04ZjYwMmNiNDIyNjYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTU0MDM5MX0.LqHJNOAFs909VfMwJbJ6ZYXYj-mjJPvhUEDa5mvrUsM

###
GET http://localhost:3000/courses/2f3f59dd-ce5c-4022-879e-bc69f0739a92
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZjEyMDEwMy1mMzIzLTRjZTAtYjFlNC04ZjYwMmNiNDIyNjYiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NTUzOTEyOX0.7Ht_1wMyh-xS1WmFh1zoIahnB0sIl-NkzqzwYpkhu_8
###
DELETE http://localhost:3000/courses/66834c18-9544-4857-96bd-0ba9c29409e5
###

PATCH  http://localhost:3000/courses/2287f75d-b438-47ff-b29a-409f332b5ffe
Content-Type: application/json

{
  "title": "Database course2" 
}

####
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "Vicente.Barros@yahoo.com",
  "password": "123456"
}